version: '3.1'
services:
  discount-service:
    image: discount-service
    build:
      context: .
    ports:
      - "8000-8020:8080"
    deploy:
      mode: replicated
      replicas: 5
#Add DB configuration instead of using in-memory DB